---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: traefik
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/description: Home Automation
    gethomepage.dev/group: Smart Home
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/href: https://ha.home.example.com
    gethomepage.dev/pod-selector: ''
    gethomepage.dev/siteMonitor: http://home-assistant.home-assistant.svc.cluster.local:8123
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.home.example.com`)
      kind: Rule
      services:
        - name: home-assistant
          namespace: home-assistant
          port: 8123
  tls:
    secretName: home-youruser-com-tls
