---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: traefik
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: Proxmox
    gethomepage.dev/description: Hypervisor
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: proxmox.png
    gethomepage.dev/href: https://proxmox.home.example.com
    gethomepage.dev/pod-selector: ''
    gethomepage.dev/siteMonitor: https://10.11.12.10:8006
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.home.example.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: proxmox-external
          port: 8006
          scheme: https
          serversTransport: insecure
  tls:
    secretName: home-youruser-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.11.12.10
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure
  namespace: traefik
spec:
  insecureSkipVerify: true
