---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: z2m
  namespace: traefik
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/description: Zigbee Bridge
    gethomepage.dev/group: Smart Home
    gethomepage.dev/icon: zigbee2mqtt.png
    gethomepage.dev/href: https://z2m.home.example.com
    gethomepage.dev/pod-selector: ''
    gethomepage.dev/siteMonitor: http://10.11.12.22:8080
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`z2m.home.example.com`)
      kind: Rule
      middlewares:
        - name: authelia-forward-auth
      services:
        - name: z2m-external
          port: 8080
          scheme: http
  tls:
    secretName: home-youruser-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: z2m-external
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: z2m-external
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.11.12.22
    ports:
      - name: http
        port: 8080
        protocol: TCP
