---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: ArgoCD
    gethomepage.dev/description: GitOps Deployments
    gethomepage.dev/group: Admin
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/href: https://argocd.home.example.com
    gethomepage.dev/pod-selector: app.kubernetes.io/name=argocd-server
    gethomepage.dev/siteMonitor: http://argocd-server.argocd.svc.cluster.local:80
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.home.example.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
          scheme: http
  tls: {}
