---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gatus
  namespace: gatus
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: Gatus
    gethomepage.dev/description: Service Status
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: gatus.png
    gethomepage.dev/href: https://status.home.example.com
    gethomepage.dev/pod-selector: app.kubernetes.io/name=gatus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`status.home.example.com`)
      kind: Rule
      services:
        - name: gatus
          port: 80
  tls:
    secretName: home-youruser-com-tls
