---
apiVersion: v1
kind: Service
metadata:
  name: freeradius
  namespace: freeradius
  labels:
    app.kubernetes.io/name: freeradius
spec:
  type: LoadBalancer
  loadBalancerIP: 10.11.12.15
  ports:
    - name: auth
      port: 1812
      targetPort: 1812
      protocol: UDP
    - name: acct
      port: 1813
      targetPort: 1813
      protocol: UDP
  selector:
    app.kubernetes.io/name: freeradius
