---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Run Tailscale configuration
  ansible.builtin.command: /usr/local/bin/tailscale-up
  changed_when: true

- name: Restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted
